### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [semwai/kotlinTar#1]
1. https://github.com/semwai/kotlinTar/blob/5ebc079f0fbb9f5fd00f8e34489c68dce98eb9a9/src/main/kotlin/ru/spbstu/semwai/Schema.kt#L14-L17 Тут лучше вместо `forEach` использовать `map`, тогда эта функция вообще будет однострочником.
1. https://github.com/semwai/kotlinTar/blob/5ebc079f0fbb9f5fd00f8e34489c68dce98eb9a9/src/main/kotlin/ru/spbstu/semwai/TarEngine.kt#L11-L15 Тут тоже лучше `map`.
1. https://github.com/semwai/kotlinTar/blob/5ebc079f0fbb9f5fd00f8e34489c68dce98eb9a9/src/main/kotlin/ru/spbstu/semwai/TarEngine.kt#L19-L21 А тут лучше `joinToString`. И запятую из `toString`, мне кажется, лучше сюда перенести.
1. Главное замечание - Вы записываете размер в байтах, а при восстановлении считаете символы. Это работает только для латиницы, но не для, например, кириллицы.
1. И ещё, что мешает восклицательному знаку встретиться в имени файла?

**Comment by semwai** [comment]
Исправил. 
Я решил работать с байтами. Во первых так программа может обрабатывать не только текстовые файлы, а во вторых, класс `File` предоставляет больше удобств для работы с файлом, т.к. можно сразу узнать размер файла. В случае работы со строками, для установления размера пришлось бы читать весь файл - `FIle("...").readText().length`. По идее это не так производительно.

**Comment by maximpetrov** [comment]
Принято, пусть будет работа с байтами. В условии, конечно, сказано, что и входной и выходной файлы должны быть текстовыми, но это не так принципиально. А по поводу производительности: Вы же всё равно читаете весь файл, чтобы скопировать его содержимое.
